Style/Documentation:
  Enabled: false
  # /Users/melo/Projects/Rails/market_place_api/.rubocop.yml:
  #   Warning: no department given for Documentation. The
  #   following cops were added to RuboCop, but are not
  #   configured. Please set Enabled to either `true` or `false` in
  #   your `.rubocop.yml` file: -
  #     Layout/EmptyLinesAroundAttributeAccessor (0.83) -
  # Layout/SpaceAroundMethodCallOperator (0.82) -
  #   Lint/DeprecatedOpenSSLConstant (0.84) -
  #     Lint/DuplicateElsifCondition (0.88) -
  #       Lint/MixedRegexpCaptureTypes (0.85) -
  # Lint/RaiseException (0.81) -
  #   Lint/StructNewOverride (0.81) -
  #     Style/AccessorGrouping (0.87) -
  #       Style/ArrayCoercion (0.88) -
  #         Style/BisectedAttrAccessor (0.87) -
  #           Style/CaseLikeIf (0.88) -
  #             Style/ExponentialNotation (0.82) -
  #               Style/HashAsLastArrayItem (0.88) -
  #                 Style/HashEachMethods (0.80) -
  #                   Style/HashLikeCase (0.88) -
  # Style/HashTransformKeys (0.80) -
  #   Style/HashTransformValues (0.80) -
  #     Style/RedundantAssignment (0.87) -
  #       Style/RedundantFetchBlock (0.86) -
  #         Style/RedundantFileExtensionInRequire (0.88) -
  #           Style/RedundantRege...
