default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: market_place_api_development

test:
  <<: *default
  database: market_place_api_test

production:
  <<: *default
  database: market_place_api_production
  username: market_place_api
  password: <%= ENV['MARKET_PLACE_API_DATABASE_PASSWORD'] %>
